# .streamlit/secrets.toml

SUPABASE_URL = "https://npvwctwurhttdzvbvgcz.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdndjdHd1cmh0dGR6dmJ2Z2N6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTU3NzQ4NSwiZXhwIjoyMDY3MTUzNDg1fQ.LoYMfHCtiGeHkot7hUV097ERpvAodP6VsbUPvpG2HUA"
ADMIN_EMAILS = ["mmueller4@rogers.com"]
